CREATE TABLE IF NOT EXISTS students (
	student_number NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name varchar(35),
    first_name varchar(35)
);

CREATE TABLE IF NOT EXISTS users (
	username varchar(35) PRIMARY KEY,
	password_hash varchar(100) NOT NULL,
	role varchar(35) NOT NULL
);

CREATE TABLE IF NOT EXISTS subjects (
	subject_id VARCHAR(25) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS rooms (
	name VARCHAR(25) PRIMARY KEY,
	capacity INT
);

CREATE TABLE IF NOT EXISTS faculty (
	faculty_number NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name varchar(35),
    first_name varchar(35)
);

CREATE INDEX IF NOT EXISTS idx_faculty_last_name ON faculty(last_name);

CREATE TABLE IF NOT EXISTS sections (
	section_id VARCHAR(25) PRIMARY KEY,
	subject_id VARCHAR(25),
	schedule VARCHAR(25),
	room_name VARCHAR(25),
	faculty_number INT,
	FOREIGN KEY (subject_id) REFERENCES subjects (subject_id),
	FOREIGN KEY (room_name) REFERENCES rooms (name),
	FOREIGN KEY (faculty_number) REFERENCES faculty (faculty_number)
);

CREATE TABLE IF NOT EXISTS enlistments (
	student_number INT,
	section_id VARCHAR(25),
	PRIMARY KEY (student_number, section_id),
	FOREIGN KEY (student_number) REFERENCES students (student_number),
	FOREIGN KEY (section_id) REFERENCES sections (section_id)
);
